"""empty message

Revision ID: 716392784d90
Revises: 9d3b9d6618a9
Create Date: 2021-03-23 17:27:04.849231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716392784d90'
down_revision = '9d3b9d6618a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_math_score', sa.Integer(), nullable=False),
    sa.Column('avg_math_score', sa.Float(), nullable=False),
    sa.Column('total_memory_score', sa.Integer(), nullable=False),
    sa.Column('avg_memory_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('totals')
    # ### end Alembic commands ###
